[project]
name = "homework"
version = "0.1.0"
description = "Homework 5"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.120.0",
    "scikit-learn==1.6.1",
    "uvicorn>=0.38.0",
]
